### PR TITLE
npm install -g loopback doesn't work

### PR DESCRIPTION
**Pull request by szihai**
use npm install -g loopback-cli instead.

### CODE REVIEW

**Comment by dokun1** [comment]
hi! 👋 I just tried the command again and it worked just fine, with output of:

```
 ~  npm install -g loopback
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
+ loopback@3.11.1
added 239 packages in 11.679s
```

What version of node and npm are you running?

**Comment by szihai** [comment]
node 8.4.0 npm 5.3.0
When I do npm install -g loopback, I got the same warning message as you. BUT npm did not install anything.
lb -v
-bash: lb: command not found
Only with loopback-cli, npm did install something and lb is working.

**Comment by dokun1** [comment]
I'll use it, because I know it works, but I'd like to investigate whether `npm install -g loopback` also works. Thanks!

**Comment by dokun1** [comment]
Interesting. I'll look into it further, because I was told by multiple people that it should work. Thank you anyway :-)

**Pull request merged**
